version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pr1de
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: telegram_bot_app
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
